# Generated by Django 2.1 on 2018-10-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('date', models.DateField(default='2005-12-01')),
                ('time', models.TimeField(default='12:10:20')),
                ('seats', models.PositiveIntegerField()),
            ],
        ),
    ]
